### PR TITLE
[BugFix] Added Error checking for Non-Existant Keys

### LINKED ISSUE #175: Error with initial book lookup when one of width, height, thickness don't exist
9781439187920 doesn't return the book

### LINKED ISSUE #203: Debug ISBN 978-1-60309-015-5 for initial book add
Seem to be getting an authors key error

### PR DESCRIPTION
**Pull request by hkder**
## Feature Description (what did you do?)
- Some relevant keys were not given from google books api. Those fields will not return null. (Closes #203, Closes #175)

## Design/Implementation Details (how did you do it?)
- Added key-checking in isbn.py

## Testing (how did you ensure this works correctly?)
- Tested with Postman on books-dev

### CODE REVIEW

**Comment by hkder** [comment]
The key will exist but it will be null. The reason for not making an empty string is that some representation in the JSON payload that is being sent is not a string but integer.

**Comment by danielfeinblatt** [comment]
> The key will exist but it will be null. The reason for not making an empty string is that some representation in the JSON payload that is being sent is not a string but integer/float/array.

After our most recent meeting, are we changing this to not including the key instead?

**Comment by caseyszilagyi** [comment]
@danielfeinblatt @hkder can we get this merged in soon? It's unclear to me what type of data I would be getting back for this book, and I need to ensure everything works properly

**Comment by hkder** [comment]
yeah this can be merged in

**Review by danielfeinblatt — APPROVED** [review]
LGTM

**Review by hkder — COMMENTED** [review]
this is resolved

**Review by caseyszilagyi — APPROVED** [review]
LGTM

**Pull request merged**
